export const selectors = {
  screenOrgSelection: '~screen-org-selection',
  screenLogin: '~action-change-org',
  screenAdminHome: '~screen-admin-home',
  screenDriverHome: '~screen-driver-home',
  screenClientHome: '~screen-client-home',
  screenCampaignDetail: '~screen-campaign-detail',
  screenProofUpload: '~screen-proof-upload',
  screenShift: '~screen-shift',
  appHeaderBack: '~app-header-back',
  loginContinue: '~action-login-continue',
  loginPassword: '~input-login-password',
  driverUploadProof: '~driver-action-upload-proof',
  driverShiftLog: '~driver-action-shift-log',
  adminQuickRoutes: '~admin-quick-routes',
  clientViewAllCampaigns: '~client-view-all-campaigns',
  orgOption: (tenant: 'lonestar' | 'skyline') => `~org-option-${tenant}`,
  roleOption: (role: 'admin' | 'driver' | 'client') => `~role-option-${role}`,
  campaignCard: (campaignId: string) => `~campaign-card-${campaignId}`,
};
